version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-get-secgrp"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-5neaqfh2mr1g"
s3_prefix = "sam-get-secgrp"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

